// <auto-generated />
using System;
using KSA_s_Finest_Sightseeing_Tours.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSAFinestSightseeingTours.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210612034432_version2")]
    partial class version2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KSA_s_Finest_Sightseeing_Tours.Models.Included", b =>
                {
                    b.Property<int>("IncludedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EntiranceFees")
                        .HasColumnType("bit");

                    b.Property<bool>("Food")
                        .HasColumnType("bit");

                    b.Property<bool>("PickUpAndDrop")
                        .HasColumnType("bit");

                    b.Property<bool>("TourGuide")
                        .HasColumnType("bit");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<bool>("Transport")
                        .HasColumnType("bit");

                    b.HasKey("IncludedId");

                    b.HasIndex("TourId");

                    b.ToTable("Includeds");
                });

            modelBuilder.Entity("KSA_s_Finest_Sightseeing_Tours.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdultPrice")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChildPrice")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DepartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(600)");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Place")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ReturnsAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("KSA_s_Finest_Sightseeing_Tours.Models.Included", b =>
                {
                    b.HasOne("KSA_s_Finest_Sightseeing_Tours.Models.Tour", "Tour")
                        .WithMany("Includeds")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("KSA_s_Finest_Sightseeing_Tours.Models.Tour", b =>
                {
                    b.Navigation("Includeds");
                });
#pragma warning restore 612, 618
        }
    }
}
