// <auto-generated />
using System;
using KSA_s_Finest_Sightseeing_Tours.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KSAFinestSightseeingTours.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210612034239_version1")]
    partial class version1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KSA_s_Finest_Sightseeing_Tours.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdultPrice")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChildPrice")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DepartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(600)");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Place")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ReturnsAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
